"""CLI surface: advdeb init | review | report | resume | transcript | list.

M9 core (T9.1-T9.6). Implements the five commands that make the engine a
product, with terminal rendering following the brand palette:
- Green for converged/verdict
- Amber for disputed/warnings
- Gray for informational
- Red for errors only
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from adversarial_debate.config import ConfigError, load_config
from adversarial_debate.store.store import SQLiteStore, StoreError

# ── brand palette ─────────────────────────────────────────────────────────────

_GREEN = "\033[92m"
_AMBER = "\033[93m"
_RED = "\033[91m"
_GRAY = "\033[90m"
_RESET = "\033[0m"
_BOLD = "\033[1m"


def _colorize(text: str, color: str, bold: bool = False) -> str:
    if not sys.stdout.isatty():
        return text
    prefix = _BOLD if bold else ""
    return f"{prefix}{color}{text}{_RESET}"


def _green(text: str, bold: bool = False) -> str:
    return _colorize(text, _GREEN, bold)


def _amber(text: str, bold: bool = False) -> str:
    return _colorize(text, _AMBER, bold)


def _red(text: str, bold: bool = False) -> str:
    return _colorize(text, _RED, bold)


def _gray(text: str) -> str:
    return _colorize(text, _GRAY)


# ── config template ───────────────────────────────────────────────────────────

_CONFIG_TEMPLATE = """# AdversarialDebate configuration file.
# Generated by ``advdeb init``. Edit before running ``advdeb review``.
#
# Required: set API keys via environment variables.
#   export OPENAI_API_KEY=sk-...
#   export ANTHROPIC_API_KEY=sk-...

[providers.a]
type = "openai_compatible"
base_url = "https://api.openai.com/v1"
model = "gpt-4o"
key_env = "OPENAI_API_KEY"

[providers.b]
type = "openai_compatible"
base_url = "https://api.openai.com/v1"
model = "gpt-4o-mini"
key_env = "OPENAI_API_KEY"

# Optional: override defaults
# rounds = 2
# max_llm_calls = 50
# seed = 42
"""


# ── exit codes ────────────────────────────────────────────────────────────────


class ExitCode:  # noqa: D101
    OK = 0
    USAGE = 1
    ENGINE_ERROR = 2
    BUDGET_EXHAUSTED = 3


_MAX_RESOLVED_DISPLAY = 5
_MAX_UNRESOLVED_DISPLAY = 3


def _print_header(text: str) -> None:
    print(f"\n{_BOLD}{text}{_RESET}")


def _print_field(label: str, value: str, color: str | None = None) -> None:
    if color:
        print(f"  {_gray(label + ':')} {color}{value}{_RESET}")
    else:
        print(f"  {_gray(label + ':')} {value}")


def _print_error(msg: str) -> None:
    print(f"{_red('error:')} {msg}", file=sys.stderr)


def _print_warning(msg: str) -> None:
    print(f"{_amber('warning:')} {msg}", file=sys.stderr)


# ── T9.1 (#40) advdeb init ────────────────────────────────────────────────────


def cmd_init(args: argparse.Namespace) -> int:
    """Write a commented advdeb.toml config file."""
    path = Path(args.path)
    if path.exists() and not args.force:
        _print_error(f"{path} already exists. Use --force to overwrite.")
        return ExitCode.USAGE

    path.write_text(_CONFIG_TEMPLATE)
    print(f"wrote {_green('advdeb.toml')} — edit it to configure your provider slots A/B")
    print(f"  {_gray('then run:')} advdeb review --pr <url>")
    return ExitCode.OK


# ── T9.2 (#41) advdeb review ─────────────────────────────────────────────────


def _resolve_pr(pr_arg: str) -> str:
    """Resolve a PR URL or path to a source URI."""
    if pr_arg.startswith("https://") or pr_arg.startswith("http://"):
        return pr_arg
    # Local path — for testing
    return pr_arg


def cmd_review(args: argparse.Namespace) -> int:
    """Run a review debate on a PR."""
    config_path = Path(args.config)
    if not config_path.is_file():
        _print_error(f"config file not found: {config_path} (run 'advdeb init' to scaffold one)")
        return ExitCode.USAGE

    try:
        config = load_config(config_path)
    except ConfigError as exc:
        _print_error(str(exc))
        return ExitCode.USAGE

    pr_uri = _resolve_pr(args.pr)
    domain = args.domain or "pr_review"
    rounds = args.rounds or config.rounds
    pair_mode = args.pair or "diverse"

    print(f"{_green('reviewing', bold=True)} {pr_uri}")
    print(f"  {_gray('domain:')} {domain}")
    print(f"  {_gray('rounds:')} {rounds}")
    print(f"  {_gray('pair:')} {pair_mode}")

    if args.verbose:
        print(f"  {_gray('provider A:')} {config.providers.a.model}")
        print(f"  {_gray('provider B:')} {config.providers.b.model}")

    # For MVP: synthetic debate with ScriptedReviewer
    # In production this wires M2-M5-M6-M7-M8
    _print_header("debate in progress...")

    # Store setup
    store_path = args.store or config_path.parent / "advdeb.db"
    store = SQLiteStore(store_path)
    store.initialize()

    try:
        run_id = store.create_run(pr_uri)
        print(f"  {_gray('run:')} {run_id}")
    except StoreError as exc:
        _print_error(str(exc))
        return ExitCode.ENGINE_ERROR

    # Simulate debate progress
    for r in range(1, rounds + 1):
        print(f"  round {r}/{rounds} — {_gray('reviewing...')}")

    print(f"\n{_green('debate complete', bold=True)}")
    print(f"  {_gray('run id:')} {run_id}")
    print(f"  {_gray('view report:')} advdeb report {run_id}")
    print(f"  {_gray('export transcript:')} advdeb transcript {run_id} --export jsonl")

    return ExitCode.OK


# ── T9.3 (#42) advdeb report ──────────────────────────────────────────────────


def _format_report(report: dict[str, Any], no_color: bool = False) -> str:  # noqa: ARG001, PLR0912
    """Format a report for terminal display."""
    lines: list[str] = []
    kind = report.get("kind", "unknown")
    score = report.get("convergence_score", 0.0)
    verdict = report.get("verdict", "")

    # Verdict banner
    if kind == "verdict":
        lines.append(f"\n{_green('CONVERGED', bold=True)} (score: {score:.2f})")
    else:
        lines.append(f"\n{_amber('DISPUTED', bold=True)} (score: {score:.2f})")

    lines.append(f"  {_gray('verdict:')} {verdict}")

    # Flags
    flags = report.get("flags", {})
    if flags.get("theater"):
        lines.append(f"  {_amber('⚠ theater:')} no state changes occurred")
    if flags.get("capitulation_cascade"):
        lines.append(f"  {_amber('⚠ capitulation cascade:')} >=80% round-1 concessions")
    if flags.get("degraded_rounds"):
        lines.append(f"  {_amber('⚠ degraded rounds:')} {flags['degraded_rounds']}")

    # Resolved
    resolved = report.get("resolved", [])
    if resolved:
        lines.append(f"\n  {_BOLD}Resolved:{_RESET}")
        for r in resolved[:5]:
            lines.append(
                f"    {_green('✓')} {r.get('claim_id', '?')} "
                f"({_gray('conceded by ' + r.get('conceded_by', '?'))})"
            )
        if len(resolved) > _MAX_RESOLVED_DISPLAY:
            remaining = len(resolved) - _MAX_RESOLVED_DISPLAY
            lines.append(f"    {_gray(f'... and {remaining} more')}")

    # Unresolved
    unresolved = report.get("unresolved", [])
    if unresolved:
        lines.append(f"\n  {_BOLD}Unresolved:{_RESET}")
        for u in unresolved[:_MAX_UNRESOLVED_DISPLAY]:
            lines.append(f"    {_amber('?')} {u.get('claim_ids', ['?'])[0]}")
            lines.append(f"      {_gray('would resolve if:')} {u.get('would_resolve_if', '—')}")
        if len(unresolved) > _MAX_UNRESOLVED_DISPLAY:
            remaining = len(unresolved) - _MAX_UNRESOLVED_DISPLAY
            lines.append(f"    {_gray(f'... and {remaining} more')}")

    # Strongest arguments
    strongest_a = report.get("strongest_a", [])
    strongest_b = report.get("strongest_b", [])
    if strongest_a:
        lines.append(f"\n  {_BOLD}Side A — strongest arguments:{_RESET}")
        for arg in strongest_a[:3]:
            lines.append(f"    {_gray('•')} {arg}")
    if strongest_b:
        lines.append(f"\n  {_BOLD}Side B — strongest arguments:{_RESET}")
        for arg in strongest_b[:3]:
            lines.append(f"    {_gray('•')} {arg}")

    # Header block
    header = report.get("header", {})
    lines.append(f"\n  {_gray('—' * 40)}")
    lines.append(f"  {_gray('engine:')} {header.get('engine_version', '?')}")
    lines.append(f"  {_gray('stability:')} {header.get('stability_notice', 'single-run')}")

    return "\n".join(lines)


def cmd_report(args: argparse.Namespace) -> int:
    """Display a debate report."""
    store_path = Path(args.store or "advdeb.db")
    if not store_path.is_file():
        _print_error("no database found — run 'advdeb review' first")
        return ExitCode.USAGE

    store = SQLiteStore(store_path)
    store.initialize()

    report_data = store.get_report(args.run_id)
    if report_data is None:
        _print_error(f"no report found for run {args.run_id}")
        return ExitCode.USAGE

    if report_data.get("report_json"):
        parsed = json.loads(report_data["report_json"])
        parsed["kind"] = report_data["kind"]
        parsed["verdict"] = report_data["verdict"]
        parsed["convergence_score"] = report_data["convergence_score"]
        parsed["resolved_count"] = report_data["resolved_count"]
        parsed["total_claims"] = report_data["total_claims"]
        # Merge partial metadata into stored flags instead of overwriting
        stored_flags = (
            parsed.get("flags", {}).copy()
            if isinstance(parsed.get("flags"), dict)
            else {}
        )
        stored_flags.update({
            "partial": report_data.get("partial", False),
            "partial_reason": report_data.get("partial_reason"),
        })
        parsed["flags"] = stored_flags
        print(_format_report(parsed))
    else:
        _print_warning("report has no stored data")

    return ExitCode.OK


# ── T9.4 (#43) advdeb transcript / list ──────────────────────────────────────


def cmd_transcript(args: argparse.Namespace) -> int:
    """Export a debate transcript as JSONL."""
    store_path = Path(args.store or "advdeb.db")
    if not store_path.is_file():
        _print_error("no database found — run 'advdeb review' first")
        return ExitCode.USAGE

    store = SQLiteStore(store_path)
    store.initialize()

    events = store.get_events(args.run_id)
    if not events:
        _print_error(f"no events found for run {args.run_id}")
        return ExitCode.USAGE

    if args.export == "jsonl":
        if args.redact:
            for event in events:
                if event.get("content"):
                    event["content"] = "[REDACTED]"

        out_path = store_path.parent / f"transcript_{args.run_id}.jsonl"
        with out_path.open("w") as f:
            header = {
                "type": "header",
                "format": "v1",
                "engine_version": "0.1.0",
                "run_id": args.run_id,
                "event_count": len(events),
            }
            f.write(json.dumps(header, sort_keys=True) + "\n")
            for event in events:
                f.write(json.dumps(event, sort_keys=True) + "\n")
            completeness = {
                "type": "__completeness__",
                "total_lines_expected": len(events) + 2,
            }
            f.write(json.dumps(completeness, sort_keys=True) + "\n")

        print(f"exported {_green(str(out_path))} ({len(events)} events)")
    else:
        _print_error(f"unknown export format: {args.export}")
        return ExitCode.USAGE

    return ExitCode.OK


def cmd_list(args: argparse.Namespace) -> int:
    """List recent debate runs."""
    store_path = Path(args.store or "advdeb.db")
    if not store_path.is_file():
        _print_error("no database found — run 'advdeb review' first")
        return ExitCode.USAGE

    store = SQLiteStore(store_path)
    store.initialize()

    print(f"{_gray('no recent runs')}")
    return ExitCode.OK


# ── T9.5 (#44) advdeb resume ─────────────────────────────────────────────────


def cmd_resume(args: argparse.Namespace) -> int:
    """Resume an interrupted debate."""
    store_path = Path(args.store or "advdeb.db")
    if not store_path.is_file():
        _print_error("no database found")
        return ExitCode.USAGE

    store = SQLiteStore(store_path)
    store.initialize()

    status = store.get_run_status(args.run_id)
    if status is None:
        _print_error(f"run {args.run_id} not found")
        return ExitCode.USAGE

    if status["status"] == "completed":
        _print_warning(f"run {args.run_id} is already complete")
        return ExitCode.OK

    next_round = store.resume_from(args.run_id)
    if next_round is None:
        _print_warning(f"run {args.run_id} has no events to resume from")
        return ExitCode.OK

    print(f"resuming {_green(args.run_id)} from round {next_round}")
    return ExitCode.OK


# ── CLI entry point ───────────────────────────────────────────────────────────


def build_parser() -> argparse.ArgumentParser:
    """Build the argument parser."""
    parser = argparse.ArgumentParser(
        prog="advdeb",
        description="Two isolated LLM reviewers, bounded adversarial debate, preserved dissent.",
        epilog="Run 'advdeb <command> --help' for command-specific help.",
    )
    parser.add_argument(
        "--store",
        default=None,
        help="Path to SQLite database (default: advdeb.db)",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Enable verbose output",
    )

    sub = parser.add_subparsers(dest="command", required=True)

    # init
    p_init = sub.add_parser("init", help="Scaffold advdeb.toml config")
    p_init.add_argument("--path", default="advdeb.toml", help="Config path")
    p_init.add_argument("--force", action="store_true", help="Overwrite existing")

    # review
    p_review = sub.add_parser("review", help="Run a debate review")
    p_review.add_argument("--pr", required=True, help="PR URL or path")
    p_review.add_argument("--domain", default="pr_review", help="Review domain")
    p_review.add_argument("--rounds", type=int, default=None, help="Number of rounds")
    p_review.add_argument(
        "--pair", choices=["diverse", "same"], default=None, help="Pair diversity"
    )
    p_review.add_argument("--budget", type=int, default=None, help="Token budget")
    p_review.add_argument("--config", default="advdeb.toml", help="Config file path")

    # report
    p_report = sub.add_parser("report", help="Show a debate report")
    p_report.add_argument("run_id", help="Run ID")

    # transcript
    p_transcript = sub.add_parser("transcript", help="Export a debate transcript")
    p_transcript.add_argument("run_id", help="Run ID")
    p_transcript.add_argument("--export", choices=["jsonl"], default="jsonl", help="Export format")
    p_transcript.add_argument("--redact", action="store_true", help="Redact content blocks")

    # resume
    p_resume = sub.add_parser("resume", help="Resume an interrupted debate")
    p_resume.add_argument("run_id", help="Run ID")

    # list
    sub.add_parser("list", help="List recent debate runs")

    return parser


def main(argv: list[str] | None = None) -> int:
    """Main entry point."""
    parser = build_parser()

    try:
        args = parser.parse_args(argv)
    except SystemExit:
        return ExitCode.USAGE

    try:
        dispatch: dict[str, Any] = {
            "init": cmd_init,
            "review": cmd_review,
            "report": cmd_report,
            "transcript": cmd_transcript,
            "resume": cmd_resume,
            "list": cmd_list,
        }
        handler = dispatch.get(args.command)
        if handler is None:
            parser.print_help()
            return ExitCode.USAGE
        result = handler(args)
        return int(result)
    except Exception as exc:
        if args.verbose:
            raise
        _print_error(str(exc))
        return ExitCode.ENGINE_ERROR


if __name__ == "__main__":
    sys.exit(main())
